### 1. Numpy: 

In [1]:
import numpy as np
# We use numpy because it is faster than the python lists

In [9]:
list1 = [1,2,3]
array1 = np.array(list1)

print(f'Normal list: {list1}, type: {type(list1)}')
print(f'Numpy list: {array1}, type: {type(array1)}')

Normal list: [1, 2, 3], type: <class 'list'>
Numpy list: [1 2 3], type: <class 'numpy.ndarray'>


In [10]:
list2 = [[1,2,3],[4,5,6]]
print(list2)
array2 = np.array(list2)
print(array2)
print(f'Just first line: {array2[0]} \nand\nmedia of matrix {np.average(array2)}')

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
Just first line: [1 2 3] 
and
media of matrix 3.5


#### Operating arrays - 2D:

In [11]:
array1 + array2

array([[2, 4, 6],
       [5, 7, 9]])

In [12]:
array1 * array2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [18]:
print(f'Before transpose version:\n {array2}')
print(f'After transpose version:\n {np.transpose(array2)}')

Before transpose version:
 [[1 2 3]
 [4 5 6]]
After transpose version:
 [[1 4]
 [2 5]
 [3 6]]


#### Initializing 2D arrays

In [28]:
# Initializing with zeros
a = np.zeros((3,5)) # (line,column)
print(a,'\nGeneral matrix',type(a),'\nand each element:',type(a[0,0]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
General matrix <class 'numpy.ndarray'> 
and each element: <class 'numpy.float64'>


In [29]:
# Initializing empty array
np.empty([3,4])

array([[4.66076515e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

#### Slicing forms:

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(b[:, 0]) #Just first column
print(b[:,1]) # Just second column

[1 4 7]
[2 5 8]


In [40]:
b[:,0:2] # two columns

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
c = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13])
# [start:stop:step]
c[1:7:2]

array([1, 3, 5])

#### Save and read files:

In [48]:
np.save('/tmp/c.npy', c)
del(c)
c = np.load('/tmp/c.npy')
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


#### obs: study about memory mapping

### 2. Pandas: